[package]
name = "tmucks"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"
description = "a tmux config manager for the reckless"

[dependencies]
ratatui = "0.26"
crossterm = "0.27"
dirs = "5.0"
clap = { version = "4.5", features = ["derive"] }
